package com.iuh.fit.recycling.itemstatus.entities;

public enum Status {
    INITIAL,
    RECEIVED,
    EXTERNAL_EVALUATING,
    EXTERNAL_EVALUATING_ACCEPTED,
    INTERNAL_EVALUATING,
    INTERNAL_EVALUATING_ACCEPTED,
    RESELL,
    RECYCLING,
    EXTERNAL_EVALUATING_CONFLIC,
    INTERNAL_EVALUATING_CONFLICT,

}
